# consistency of self calls
We are trying to see how reliably self echoes are heard and how consistent they are in the information they provide as oppposed to information coming from other direct calls/ echeos from their direct calls

Let us first load the data.

In [2]:
import sys
import os 
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
import itertools
import pickle
from mpl_toolkits.axes_grid1 import make_axes_locatable
os.chdir("/home/adityamoger/Documents/GitHub/dynamic_model_of_cocktail_party_nightmare/")

sys.path.append("./exploratory_analysis/")
sys.path.append("./dynamic_model/")

from supporting_files.read_simulation_output import read_data_per_simulation_per_bat
from supporting_files.utilities import make_dir

import bisect
import pandas as pd
plt.style.use("dark_background")

In [2]:
def make_ordered_lists_of_params(array_of_parameter_lists):
    product_of_lists = list(itertools.product(*array_of_parameter_lists))
    return product_of_lists

def reformat_matrices(nan_matrix, track_unique_objects):
    
    nan_matrix = nan_matrix.T
    
    sorting_indices = np.argsort(track_unique_objects)
    nan_matrix = nan_matrix[sorting_indices]
    track_unique_objects = np.array(track_unique_objects)[sorting_indices]
    
    # nan_matrix = nan_matrix[:, ~np.isnan(nan_matrix).all(0)]
    masked_array = np.ma.array(nan_matrix, mask=np.isnan(nan_matrix))
    
    return nan_matrix, track_unique_objects, masked_array

In [5]:
TEMPORAL_MASKING_DIR = "./JammingExperiment/Data/InputData/temporal_masking_fn.csv"
DIRECTORY = f"./JammingExperiment/Data/IntermediateData/debug8/"
DIRECTORY_STORE_PLOTS = "./JammingExperiment/Output/DataAppendixOutput"

In [6]:
dictionary_to_store_all_sounds = {}
dictionary_to_store_heard_sounds = {}
#keys of dictionary will be  the ordered param lists

track_unique_objects = []
sounds_to_plot = []
times_of_sounds_to_plot = []
delta_t = []
OUTPUT_DIR = DIRECTORY + f"/{0}/"
received_sounds_sorted_by_time = read_data_per_simulation_per_bat(
    OUTPUT_DIR, "received"
)
# print(received_sounds_sorted_by_time)
if len(received_sounds_sorted_by_time)==0:
    raise ValueError("empty dir")

print(received_sounds_sorted_by_time)

160
([array([], dtype=float64), array([{'all_spl_values': [np.float64(76.47712477134094), np.float64(76.47920404039166)], 'occurance_times': [np.float64(0.073), np.float64(0.074)], 'ids': [UUID('064a7593-b3e6-4295-9a74-df5f0b7e27ee'), UUID('064a7593-b3e6-4295-9a74-df5f0b7e27ee')], 'origin': (np.int64(9), np.int64(0)), 'emitter_id': 17, 'bat_direction': Vector(0.881, 0.474), 'incident_direction': Vector(3.811, -3.621), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('064a7593-b3e6-4295-9a74-df5f0b7e27ee'), 'bat_last_call_time': np.float64(0.071), 'sound_direction': Vector(0.000, 1.000), 'theta': np.float64(-77.82904113297879), 'bat_position': Vector(5.189, 3.621), 'distance_from_bat': 5.256719018180447, 'creation_time': np.float64(0.057), 'received_spl': np.float64(76.478), 'time': np.float64(0.073), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(71.63920490983456), np.float64(71.64168805388533)], 'occurance_times': [np.float64(0.073), np.float64(0.074)], 'ids': [UUID('a9a95fb8-58b8-428a-a2a7-8c5dee863ef1'), UUID('a9a95fb8-58b8-428a-a2a7-8c5dee863ef1')], 'origin': (np.float64(8.6701), np.float64(0.0)), 'emitter_id': 17, 'bat_direction': Vector(0.881, 0.474), 'incident_direction': Vector(3.481, -3.621), 'type': 'echo', 'reflected_from': 'wall_obstacle_61', 'sound_object_id': UUID('a9a95fb8-58b8-428a-a2a7-8c5dee863ef1'), 'bat_last_call_time': np.float64(0.071), 'sound_direction': Vector(1.000, 0.000), 'theta': np.float64(-80.42230062194388), 'bat_position': Vector(5.189, 3.621), 'distance_from_bat': 5.022720513636012, 'creation_time': np.float64(0.057961807580174926), 'received_spl': np.float64(71.64), 'time': np.float64(0.073), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(70.77840337565308), np.float64(70.78441237639262)], 'occurance_times': [np.float64(0.074), np.float64(0.075)], 'ids': [UUID('abf89bc0-c1c1-4469-bc9d-50dd3969f673'), UUID('abf89bc0-c1c1-4469-bc9d-50dd3969f673')], 'origin': (np.float64(10.0), np.float64(2.0399)), 'emitter_id': 19, 'bat_direction': Vector(0.881, 0.474), 'incident_direction': Vector(4.808, -1.583), 'type': 'echo', 'reflected_from': 'wall_obstacle_16', 'sound_object_id': UUID('abf89bc0-c1c1-4469-bc9d-50dd3969f673'), 'bat_last_call_time': np.float64(0.071), 'sound_direction': Vector(0.000, -1.000), 'theta': np.float64(-52.50950636049957), 'bat_position': Vector(5.192, 3.623), 'distance_from_bat': 5.061713055409206, 'creation_time': np.float64(0.05911632653061224), 'received_spl': np.float64(70.781), 'time': np.float64(0.074), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(76.57486499138862), np.float64(76.5753512374413)], 'occurance_times': [np.float64(0.169), np.float64(0.17)], 'ids': [UUID('151cdd0b-0bd7-429f-9d56-bc7465b85cd6'), UUID('151cdd0b-0bd7-429f-9d56-bc7465b85cd6')], 'origin': (np.int64(9), np.int64(0)), 'emitter_id': 17, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(3.647, -3.735), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('151cdd0b-0bd7-429f-9d56-bc7465b85cd6'), 'bat_last_call_time': np.float64(0.163), 'sound_direction': Vector(0.000, 1.000), 'theta': np.float64(-79.97302792530641), 'bat_position': Vector(5.353, 3.735), 'distance_from_bat': 5.2206161279680385, 'creation_time': np.float64(0.153), 'received_spl': np.float64(76.575), 'time': np.float64(0.169), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(71.31974294829823), np.float64(71.32189005330692)], 'occurance_times': [np.float64(0.27), np.float64(0.271)], 'ids': [UUID('d81aaf34-92b7-41a5-af3c-19baff418a55'), UUID('d81aaf34-92b7-41a5-af3c-19baff418a55')], 'origin': (np.float64(10.0), np.float64(2.0399)), 'emitter_id': 19, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(4.498, -1.831), 'type': 'echo', 'reflected_from': 'wall_obstacle_16', 'sound_object_id': UUID('d81aaf34-92b7-41a5-af3c-19baff418a55'), 'bat_last_call_time': np.float64(0.261), 'sound_direction': Vector(0.000, -1.000), 'theta': np.float64(-56.43760305531477), 'bat_position': Vector(5.502, 3.871), 'distance_from_bat': 4.856051956764878, 'creation_time': np.float64(0.2551163265306122), 'received_spl': np.float64(71.321), 'time': np.float64(0.27), 'duration': np.float64(0.002)}],
      dtype=object), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([{'all_spl_values': [np.float64(71.0148493130435), np.float64(71.02499185991468)], 'occurance_times': [np.float64(0.849), np.float64(0.85)], 'ids': [UUID('8541466b-c010-4a32-a65f-22cb79ac51e8'), UUID('8541466b-c010-4a32-a65f-22cb79ac51e8')], 'origin': (np.float64(9.6901), np.float64(7.0)), 'emitter_id': 24, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(2.903, 1.960), 'type': 'echo', 'reflected_from': 'wall_obstacle_44', 'sound_object_id': UUID('8541466b-c010-4a32-a65f-22cb79ac51e8'), 'bat_last_call_time': np.float64(0.842), 'sound_direction': Vector(1.000, 0.000), 'theta': np.float64(-0.2591713456947389), 'bat_position': Vector(6.787, 5.040), 'distance_from_bat': 3.5030987266704314, 'creation_time': np.float64(0.837903498542274), 'received_spl': np.float64(71.02), 'time': np.float64(0.849), 'duration': np.float64(0.002)}],
      dtype=object), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([], dtype=float64), array([{'all_spl_values': [np.float64(72.91551792277818), np.float64(72.92269248317041)], 'occurance_times': [np.float64(1.165), np.float64(1.166)], 'ids': [UUID('381e6d89-3ca2-4a76-8703-49cb1800c62a'), UUID('381e6d89-3ca2-4a76-8703-49cb1800c62a')], 'origin': (np.int64(10), np.int64(5)), 'emitter_id': 22, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(2.512, -0.678), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('381e6d89-3ca2-4a76-8703-49cb1800c62a'), 'bat_last_call_time': np.float64(1.161), 'sound_direction': Vector(-1.000, 0.000), 'theta': np.float64(-49.393878931716245), 'bat_position': Vector(7.488, 5.678), 'distance_from_bat': 2.6014384566235655, 'creation_time': np.float64(1.157), 'received_spl': np.float64(72.919), 'time': np.float64(1.165), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(71.42776859775311), np.float64(71.43504197010805)], 'occurance_times': [np.float64(1.165), np.float64(1.166)], 'ids': [UUID('deac6265-0db6-409d-84c1-7e6daece3385'), UUID('deac6265-0db6-409d-84c1-7e6daece3385')], 'origin': (np.float64(10.0), np.float64(5.0999)), 'emitter_id': 22, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(2.512, -0.578), 'type': 'echo', 'reflected_from': 'wall_obstacle_22', 'sound_object_id': UUID('deac6265-0db6-409d-84c1-7e6daece3385'), 'bat_last_call_time': np.float64(1.161), 'sound_direction': Vector(0.000, -1.000), 'theta': np.float64(-47.24916419622486), 'bat_position': Vector(7.488, 5.678), 'distance_from_bat': 2.577211212454268, 'creation_time': np.float64(1.157291253644315), 'received_spl': np.float64(71.431), 'time': np.float64(1.165), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(70.27337769277699), np.float64(70.28450456844926)], 'occurance_times': [np.float64(1.216), np.float64(1.217)], 'ids': [UUID('c0791f9f-0418-4fee-8fa2-404666f6ae34'), UUID('c0791f9f-0418-4fee-8fa2-404666f6ae34')], 'origin': (np.int64(10), np.int64(8)), 'emitter_id': 25, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(2.398, 2.219), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('c0791f9f-0418-4fee-8fa2-404666f6ae34'), 'bat_last_call_time': np.float64(1.21), 'sound_direction': Vector(-1.000, 0.000), 'theta': np.float64(8.48774123604153), 'bat_position': Vector(7.602, 5.781), 'distance_from_bat': 3.2674685617462336, 'creation_time': np.float64(1.206), 'received_spl': np.float64(70.279), 'time': np.float64(1.216), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(71.04569674097105), np.float64(71.05385173594318)], 'occurance_times': [np.float64(1.218), np.float64(1.219)], 'ids': [UUID('2a548547-916f-46b5-bd2e-4a92d891e01b'), UUID('2a548547-916f-46b5-bd2e-4a92d891e01b')], 'origin': (np.float64(7.14003), np.float64(6.99991)), 'emitter_id': 0, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(-0.466, 1.215), 'type': 'echo', 'reflected_from': 'wall_obstacle_39', 'sound_object_id': UUID('2a548547-916f-46b5-bd2e-4a92d891e01b'), 'bat_last_call_time': np.float64(1.21), 'sound_direction': Vector(0.340, -0.940), 'theta': np.float64(76.6984304113027), 'bat_position': Vector(7.606, 5.785), 'distance_from_bat': 1.3012781206951878, 'creation_time': np.float64(1.2138231412283296), 'received_spl': np.float64(71.05), 'time': np.float64(1.218), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(70.22699795273667), np.float64(70.22790530487538)], 'occurance_times': [np.float64(1.22), np.float64(1.221)], 'ids': [UUID('612ddb57-cbbc-4e48-8418-6711f5319234'), UUID('612ddb57-cbbc-4e48-8418-6711f5319234')], 'origin': (np.float64(6.63006), np.float64(6.99992)), 'emitter_id': 0, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(-0.980, 1.211), 'type': 'echo', 'reflected_from': 'wall_obstacle_38', 'sound_object_id': UUID('612ddb57-cbbc-4e48-8418-6711f5319234'), 'bat_last_call_time': np.float64(1.21), 'sound_direction': Vector(0.613, -0.790), 'theta': np.float64(94.70802976126811), 'bat_position': Vector(7.611, 5.789), 'distance_from_bat': 1.5580976467474688, 'creation_time': np.float64(1.2145491186946775), 'received_spl': np.float64(70.227), 'time': np.float64(1.22), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(71.6201837732134), np.float64(71.63651441883513)], 'occurance_times': [np.float64(1.269), np.float64(1.27)], 'ids': [UUID('115ff4a1-dd51-4a65-803e-decbf242ebea'), UUID('115ff4a1-dd51-4a65-803e-decbf242ebea')], 'origin': (np.float64(7.65), np.float64(6.9999)), 'emitter_id': 0, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(-0.069, 1.112), 'type': 'echo', 'reflected_from': 'wall_obstacle_40', 'sound_object_id': UUID('115ff4a1-dd51-4a65-803e-decbf242ebea'), 'bat_last_call_time': np.float64(1.262), 'sound_direction': Vector(0.046, -0.999), 'theta': np.float64(59.27834461596228), 'bat_position': Vector(7.719, 5.888), 'distance_from_bat': 1.1140786995540306, 'creation_time': np.float64(1.265292296458847), 'received_spl': np.float64(71.628), 'time': np.float64(1.269), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(72.8105436072065), np.float64(72.81635299816067)], 'occurance_times': [np.float64(1.27), np.float64(1.271)], 'ids': [UUID('a6e0a1ee-e18b-4122-b7e2-7b7e46f7f66e'), UUID('a6e0a1ee-e18b-4122-b7e2-7b7e46f7f66e')], 'origin': (np.float64(7.14004), np.float64(6.99991)), 'emitter_id': 0, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(-0.582, 1.110), 'type': 'echo', 'reflected_from': 'wall_obstacle_39', 'sound_object_id': UUID('a6e0a1ee-e18b-4122-b7e2-7b7e46f7f66e'), 'bat_last_call_time': np.float64(1.262), 'sound_direction': Vector(0.446, -0.895), 'theta': np.float64(83.361770965586), 'bat_position': Vector(7.722, 5.890), 'distance_from_bat': 1.2530133511259964, 'creation_time': np.float64(1.265673806915055), 'received_spl': np.float64(72.813), 'time': np.float64(1.27), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(71.36475707807907), np.float64(71.37663782438548)], 'occurance_times': [np.float64(1.311), np.float64(1.312)], 'ids': [UUID('ccd2e7eb-5eba-4768-ad5b-6983654e7d49'), UUID('ccd2e7eb-5eba-4768-ad5b-6983654e7d49')], 'origin': (np.int64(10), np.int64(8)), 'emitter_id': 25, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(2.187, 2.027), 'type': 'direct', 'reflected_from': None, 'sound_object_id': UUID('ccd2e7eb-5eba-4768-ad5b-6983654e7d49'), 'bat_last_call_time': np.float64(1.306), 'sound_direction': Vector(-1.000, 0.000), 'theta': np.float64(8.533382447106248), 'bat_position': Vector(7.813, 5.973), 'distance_from_bat': 2.9823401056888197, 'creation_time': np.float64(1.302), 'received_spl': np.float64(71.371), 'time': np.float64(1.311), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(73.76883212395495), np.float64(73.78398975087708)], 'occurance_times': [np.float64(1.313), np.float64(1.314)], 'ids': [UUID('c49423d8-a9fe-4e18-a692-e463e7855528'), UUID('c49423d8-a9fe-4e18-a692-e463e7855528')], 'origin': (np.float64(7.65001), np.float64(6.9999)), 'emitter_id': 0, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(-0.167, 1.023), 'type': 'echo', 'reflected_from': 'wall_obstacle_40', 'sound_object_id': UUID('c49423d8-a9fe-4e18-a692-e463e7855528'), 'bat_last_call_time': np.float64(1.306), 'sound_direction': Vector(0.142, -0.990), 'theta': np.float64(64.98157946850671), 'bat_position': Vector(7.817, 5.977), 'distance_from_bat': 1.0365792307874975, 'creation_time': np.float64(1.3090608166226967), 'received_spl': np.float64(73.776), 'time': np.float64(1.313), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(74.1728076656128), np.float64(74.17625921280704)], 'occurance_times': [np.float64(1.314), np.float64(1.315)], 'ids': [UUID('0f6e231f-0bf5-4661-974c-b5f4ed668e51'), UUID('0f6e231f-0bf5-4661-974c-b5f4ed668e51')], 'origin': (np.float64(7.14005), np.float64(6.99992)), 'emitter_id': 0, 'bat_direction': Vector(0.741, 0.672), 'incident_direction': Vector(-0.679, 1.021), 'type': 'echo', 'reflected_from': 'wall_obstacle_39', 'sound_object_id': UUID('0f6e231f-0bf5-4661-974c-b5f4ed668e51'), 'bat_last_call_time': np.float64(1.306), 'sound_direction': Vector(0.536, -0.844), 'theta': np.float64(89.34183966401423), 'bat_position': Vector(7.819, 5.979), 'distance_from_bat': 1.226293019836613, 'creation_time': np.float64(1.3095879130064392), 'received_spl': np.float64(74.175), 'time': np.float64(1.314), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(76.05934755850684), np.float64(76.06898338234501)], 'occurance_times': [np.float64(1.362), np.float64(1.363)], 'ids': [UUID('2b4678d1-8fd1-4013-9ecc-c74be034216b'), UUID('2b4678d1-8fd1-4013-9ecc-c74be034216b')], 'origin': (np.float64(7.65003), np.float64(6.9999)), 'emitter_id': 0, 'bat_direction': Vector(0.814, 0.581), 'incident_direction': Vector(-0.282, 0.932), 'type': 'echo', 'reflected_from': 'wall_obstacle_40', 'sound_object_id': UUID('2b4678d1-8fd1-4013-9ecc-c74be034216b'), 'bat_last_call_time': np.float64(1.356), 'sound_direction': Vector(0.270, -0.963), 'theta': np.float64(72.54612270132026), 'bat_position': Vector(7.932, 6.068), 'distance_from_bat': 0.9733142000916251, 'creation_time': np.float64(1.358857804743498), 'received_spl': np.float64(76.064), 'time': np.float64(1.362), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(72.50667542467717), np.float64(72.52955729285003)], 'occurance_times': [np.float64(1.362), np.float64(1.363)], 'ids': [UUID('071172e8-307b-4daf-aa60-3ea743a11c73'), UUID('071172e8-307b-4daf-aa60-3ea743a11c73')], 'origin': (np.float64(8.15997), np.float64(6.9999)), 'emitter_id': 0, 'bat_direction': Vector(0.814, 0.581), 'incident_direction': Vector(0.228, 0.932), 'type': 'echo', 'reflected_from': 'wall_obstacle_41', 'sound_object_id': UUID('071172e8-307b-4daf-aa60-3ea743a11c73'), 'bat_last_call_time': np.float64(1.356), 'sound_direction': Vector(-0.251, -0.968), 'theta': np.float64(41.955832429414784), 'bat_position': Vector(7.932, 6.068), 'distance_from_bat': 0.9591065438729943, 'creation_time': np.float64(1.3588428412893145), 'received_spl': np.float64(72.518), 'time': np.float64(1.362), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(70.1405057944562)], 'occurance_times': [np.float64(1.46)], 'ids': [UUID('147d7bfb-f13a-4f72-838d-7cb95cd16632')], 'origin': (np.float64(10.0), np.float64(4.5901)), 'emitter_id': 22, 'bat_direction': Vector(0.941, 0.340), 'incident_direction': Vector(1.894, -1.571), 'type': 'echo', 'reflected_from': 'wall_obstacle_21', 'sound_object_id': UUID('147d7bfb-f13a-4f72-838d-7cb95cd16632'), 'bat_last_call_time': np.float64(1.458), 'sound_direction': Vector(0.000, 1.000), 'theta': np.float64(-73.95938429584226), 'bat_position': Vector(8.106, 6.161), 'distance_from_bat': 2.4602662256755874, 'creation_time': np.float64(1.4511950437317784), 'received_spl': np.float64(70.141), 'time': np.float64(1.46), 'duration': np.float64(0.001)},
       {'all_spl_values': [np.float64(75.96008632889652), np.float64(75.96939875037228)], 'occurance_times': [np.float64(1.463), np.float64(1.464)], 'ids': [UUID('620f0fdc-833e-49be-933d-d708700a548f'), UUID('620f0fdc-833e-49be-933d-d708700a548f')], 'origin': (np.float64(8.15999), np.float64(6.9999)), 'emitter_id': 0, 'bat_direction': Vector(0.941, 0.340), 'incident_direction': Vector(0.046, 0.837), 'type': 'echo', 'reflected_from': 'wall_obstacle_41', 'sound_object_id': UUID('620f0fdc-833e-49be-933d-d708700a548f'), 'bat_last_call_time': np.float64(1.458), 'sound_direction': Vector(-0.068, -0.998), 'theta': np.float64(52.54914395270513), 'bat_position': Vector(8.114, 6.163), 'distance_from_bat': 0.8377953655278836, 'creation_time': np.float64(1.4604564537136144), 'received_spl': np.float64(75.965), 'time': np.float64(1.463), 'duration': np.float64(0.002)}],
      dtype=object), array([{'all_spl_values': [np.float64(79.3640530144301), np.float64(79.36797264648374)], 'occurance_times': [np.float64(1.572), np.float64(1.573)], 'ids': [UUID('6b437588-9998-401d-baec-dbbd16d73fab'), UUID('6b437588-9998-401d-baec-dbbd16d73fab')], 'origin': (np.float64(8.16002), np.float64(6.9999)), 'emitter_id': 0, 'bat_direction': Vector(0.941, 0.340), 'incident_direction': Vector(-0.159, 0.762), 'type': 'echo', 'reflected_from': 'wall_obstacle_41', 'sound_object_id': UUID('6b437588-9998-401d-baec-dbbd16d73fab'), 'bat_last_call_time': np.float64(1.567), 'sound_direction': Vector(0.189, -0.982), 'theta': np.float64(67.4682373029508), 'bat_position': Vector(8.319, 6.237), 'distance_from_bat': 0.77873814751815, 'creation_time': np.float64(1.5692755813624073), 'received_spl': np.float64(79.366), 'time': np.float64(1.572), 'duration': np.float64(0.002)},
       {'all_spl_values': [np.float64(73.90630581630221), np.float64(73.92247804145973)], 'occurance_times': [np.float64(1.572), np.float64(1.573)], 'ids': [UUID('4d5eba45-4a8a-483b-962f-05bd2cb37d28'), UUID('4d5eba45-4a8a-483b-962f-05bd2cb37d28')], 'origin': (np.float64(8.66996), np.float64(6.99991)), 'emitter_id': 0, 'bat_direction': Vector(0.941, 0.340), 'incident_direction': Vector(0.351, 0.762), 'type': 'echo', 'reflected_from': 'wall_obstacle_42', 'sound_object_id': UUID('4d5eba45-4a8a-483b-962f-05bd2cb37d28'), 'bat_last_call_time': np.float64(1.567), 'sound_direction': Vector(-0.428, -0.904), 'theta': np.float64(30.97437071078952), 'bat_position': Vector(8.319, 6.237), 'distance_from_bat': 0.8394358794452379, 'creation_time': np.float64(1.5694720250058352), 'received_spl': np.float64(73.914), 'time': np.float64(1.572), 'duration': np.float64(0.002)},

In [7]:
received_sounds_sorted_by_time[0][1][0]

{'all_spl_values': [np.float64(76.47712477134094),
  np.float64(76.47920404039166)],
 'occurance_times': [np.float64(0.073), np.float64(0.074)],
 'ids': [UUID('064a7593-b3e6-4295-9a74-df5f0b7e27ee'),
  UUID('064a7593-b3e6-4295-9a74-df5f0b7e27ee')],
 'origin': (np.int64(9), np.int64(0)),
 'emitter_id': 17,
 'bat_direction': Vector(0.881, 0.474),
 'incident_direction': Vector(3.811, -3.621),
 'type': 'direct',
 'reflected_from': None,
 'sound_object_id': UUID('064a7593-b3e6-4295-9a74-df5f0b7e27ee'),
 'bat_last_call_time': np.float64(0.071),
 'sound_direction': Vector(0.000, 1.000),
 'theta': np.float64(-77.82904113297879),
 'bat_position': Vector(5.189, 3.621),
 'distance_from_bat': 5.256719018180447,
 'creation_time': np.float64(0.057),
 'received_spl': np.float64(76.478),
 'time': np.float64(0.073),
 'duration': np.float64(0.002)}

In [8]:
new_df = pd.DataFrame()
new_df
# for key in new_df.keys():
#     new_df[key] = []
    
print(new_df)

for i, call_frame in enumerate(received_sounds_sorted_by_time[0]):
    for j, sound in enumerate(call_frame):
        for key in sound.keys():
            if isinstance(sound[key], list):
                sound[key] = sound[key][0]
        
        _sound_df = pd.DataFrame(sound)
        new_df = pd.concat((new_df,_sound_df))
        
new_df

Empty DataFrame
Columns: []
Index: []

,all_spl_values,occurance_times,ids,origin,emitter_id,bat_direction,incident_direction,type,reflected_from,sound_object_id,bat_last_call_time,sound_direction,theta,bat_position,distance_from_bat,creation_time,received_spl,time,duration
0,76.477125,0.073,064a7593-b3e6-4295-9a74-df5f0b7e27ee,9.0000,17,"Vector(0.881, 0.474)","Vector(3.811, -3.621)",direct,None,064a7593-b3e6-4295-9a74-df5f0b7e27ee,0.071,"Vector(0.000, 1.000)",-77.829041,"Vector(5.189, 3.621)",5.256719,0.057000,76.478,0.073,0.002
1,76.477125,0.073,064a7593-b3e6-4295-9a74-df5f0b7e27ee,0.0000,17,"Vector(0.881, 0.474)","Vector(3.811, -3.621)",direct,None,064a7593-b3e6-4295-9a74-df5f0b7e27ee,0.071,"Vector(0.000, 1.000)",-77.829041,"Vector(5.189, 3.621)",5.256719,0.057000,76.478,0.073,0.002
0,71.639205,0.073,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,8.6701,17,"Vector(0.881, 0.474)","Vector(3.481, -3.621)",echo,wall_obstacle_61,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,0.071,"Vector(1.000, 0.000)",-80.422301,"Vector(5.189, 3.621)",5.022721,0.057962,71.640,0.073,0.002
1,71.639205,0.073,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,0.0000,17,"Vector(0.881, 0.474)","Vector(3.481, -3.621)",echo,wall_obstacle_61,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,0.071,"Vector(1.000, 0.000)",-80.422301,"Vector(5.189, 3.621)",5.022721,0.057962,71.640,0.073,0.002
0,70.778403,0.074,abf89bc0-c1c1-4469-bc9d-50dd3969f673,10.0000,19,"Vector(0.881, 0.474)","Vector(4.808, -1.583)",echo,wall_obstacle_16,abf89bc0-c1c1-4469-bc9d-50dd3969f673,0.071,"Vector(0.000, -1.000)",-52.509506,"Vector(5.192, 3.623)",5.061713,0.059116,70.781,0.074,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,71.537063,9.894,146480d2-106e-4093-9470-5ce8c303e434,0.0000,11,"Vector(-0.962, -0.274)","Vector(-5.175, -4.776)",direct,None,146480d2-106e-4093-9470-5ce8c303e434,9.885,"Vector(0.000, 1.000)",-171.586791,"Vector(8.175, 4.776)",7.042117,9.873000,71.540,9.894,0.002
0,70.434756,9.932,0a60077b-e8b9-4df1-80f3-1678a8eedc93,0.0000,8,"Vector(-0.962, -0.274)","Vector(-8.066, 4.255)",direct,None,0a60077b-e8b9-4df1-80f3-1678a8eedc93,9.926,"Vector(1.000, 0.000)",117.895970,"Vector(8.066, 4.745)",9.119397,9.905000,70.437,9.932,0.002
1,70.434756,9.932,0a60077b-e8b9-4df1-80f3-1678a8eedc93,9.0000,8,"Vector(-0.962, -0.274)","Vector(-8.066, 4.255)",direct,None,0a60077b-e8b9-4df1-80f3-1678a8eedc93,9.926,"Vector(1.000, 0.000)",117.895970,"Vector(8.066, 4.745)",9.119397,9.905000,70.437,9.932,0.002
0,71.284287,9.936,2f60c99c-b90a-4104-9029-2b6c1b33af28,0.0000,7,"Vector(-0.962, -0.274)","Vector(-8.054, 3.259)",direct,None,2f60c99c-b90a-4104-9029-2b6c1b33af28,9.926,"Vector(1.000, 0.000)",123.683797,"Vector(8.054, 4.741)",8.688413,9.910000,71.286,9.936,0.002
1,71.284287,9.936,2f60c99c-b90a-4104-9029-2b6c1b33af28,8.0000,7,"Vector(-0.962, -0.274)","Vector(-8.054, 3.259)",direct,None,2f60c99c-b90a-4104-9029-2b6c1b33af28,9.926,"Vector(1.000, 0.000)",123.683797,"Vector(8.054, 4.741)",8.688413,9.910000,71.286,9.936,0.002

In [9]:
new_df.sort_values("time")

,all_spl_values,occurance_times,ids,origin,emitter_id,bat_direction,incident_direction,type,reflected_from,sound_object_id,bat_last_call_time,sound_direction,theta,bat_position,distance_from_bat,creation_time,received_spl,time,duration
0,76.477125,0.073,064a7593-b3e6-4295-9a74-df5f0b7e27ee,9.0000,17,"Vector(0.881, 0.474)","Vector(3.811, -3.621)",direct,None,064a7593-b3e6-4295-9a74-df5f0b7e27ee,0.071,"Vector(0.000, 1.000)",-77.829041,"Vector(5.189, 3.621)",5.256719,0.057000,76.478,0.073,0.002
1,76.477125,0.073,064a7593-b3e6-4295-9a74-df5f0b7e27ee,0.0000,17,"Vector(0.881, 0.474)","Vector(3.811, -3.621)",direct,None,064a7593-b3e6-4295-9a74-df5f0b7e27ee,0.071,"Vector(0.000, 1.000)",-77.829041,"Vector(5.189, 3.621)",5.256719,0.057000,76.478,0.073,0.002
0,71.639205,0.073,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,8.6701,17,"Vector(0.881, 0.474)","Vector(3.481, -3.621)",echo,wall_obstacle_61,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,0.071,"Vector(1.000, 0.000)",-80.422301,"Vector(5.189, 3.621)",5.022721,0.057962,71.640,0.073,0.002
1,71.639205,0.073,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,0.0000,17,"Vector(0.881, 0.474)","Vector(3.481, -3.621)",echo,wall_obstacle_61,a9a95fb8-58b8-428a-a2a7-8c5dee863ef1,0.071,"Vector(1.000, 0.000)",-80.422301,"Vector(5.189, 3.621)",5.022721,0.057962,71.640,0.073,0.002
0,70.778403,0.074,abf89bc0-c1c1-4469-bc9d-50dd3969f673,10.0000,19,"Vector(0.881, 0.474)","Vector(4.808, -1.583)",echo,wall_obstacle_16,abf89bc0-c1c1-4469-bc9d-50dd3969f673,0.071,"Vector(0.000, -1.000)",-52.509506,"Vector(5.192, 3.623)",5.061713,0.059116,70.781,0.074,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,71.537063,9.894,146480d2-106e-4093-9470-5ce8c303e434,0.0000,11,"Vector(-0.962, -0.274)","Vector(-5.175, -4.776)",direct,None,146480d2-106e-4093-9470-5ce8c303e434,9.885,"Vector(0.000, 1.000)",-171.586791,"Vector(8.175, 4.776)",7.042117,9.873000,71.540,9.894,0.002
0,70.434756,9.932,0a60077b-e8b9-4df1-80f3-1678a8eedc93,0.0000,8,"Vector(-0.962, -0.274)","Vector(-8.066, 4.255)",direct,None,0a60077b-e8b9-4df1-80f3-1678a8eedc93,9.926,"Vector(1.000, 0.000)",117.895970,"Vector(8.066, 4.745)",9.119397,9.905000,70.437,9.932,0.002
1,70.434756,9.932,0a60077b-e8b9-4df1-80f3-1678a8eedc93,9.0000,8,"Vector(-0.962, -0.274)","Vector(-8.066, 4.255)",direct,None,0a60077b-e8b9-4df1-80f3-1678a8eedc93,9.926,"Vector(1.000, 0.000)",117.895970,"Vector(8.066, 4.745)",9.119397,9.905000,70.437,9.932,0.002
0,71.284287,9.936,2f60c99c-b90a-4104-9029-2b6c1b33af28,0.0000,7,"Vector(-0.962, -0.274)","Vector(-8.054, 3.259)",direct,None,2f60c99c-b90a-4104-9029-2b6c1b33af28,9.926,"Vector(1.000, 0.000)",123.683797,"Vector(8.054, 4.741)",8.688413,9.910000,71.286,9.936,0.002
1,71.284287,9.936,2f60c99c-b90a-4104-9029-2b6c1b33af28,8.0000,7,"Vector(-0.962, -0.274)","Vector(-8.054, 3.259)",direct,None,2f60c99c-b90a-4104-9029-2b6c1b33af28,9.926,"Vector(1.000, 0.000)",123.683797,"Vector(8.054, 4.741)",8.688413,9.910000,71.286,9.936,0.002

In [10]:
new_df["delta_t"] = new_df["time"]-new_df["bat_last_call_time"]
new_df = new_df.reset_index()

In [11]:
np.unique(new_df["bat_last_call_time"].values)

array([0.071, 0.163, 0.261, 0.842, 1.161, 1.21 , 1.262, 1.306, 1.356,
       1.458, 1.567, 1.62 , 1.721, 1.829, 1.872, 1.926, 1.97 , 2.071,
       2.163, 2.267, 2.367, 2.412, 2.456, 2.548, 2.656, 2.755, 2.864,
       2.971, 3.08 , 3.172, 3.221, 3.265, 3.316, 3.374, 3.425, 3.535,
       3.644, 3.738, 3.782, 3.876, 3.978, 4.081, 4.239, 4.289, 4.395,
       4.488, 4.585, 4.688, 4.733, 4.786, 4.828, 4.87 , 4.923, 5.016,
       5.116, 5.226, 5.327, 5.479, 5.524, 5.576, 5.629, 5.683, 5.732,
       5.791, 5.892, 5.991, 6.084, 6.13 , 6.177, 6.236, 6.294, 6.409,
       6.451, 6.496, 6.734, 6.832, 6.879, 6.926, 7.08 , 7.125, 7.183,
       7.225, 7.28 , 7.34 , 7.565, 7.725, 7.919, 7.973, 8.029, 8.087,
       8.146, 8.194, 8.254, 8.349, 8.442, 8.542, 8.649, 8.705, 8.759,
       8.814, 8.868, 8.914, 8.971, 9.025, 9.131, 9.23 , 9.331, 9.483,
       9.529, 9.576, 9.621, 9.667, 9.826, 9.885, 9.926])

In [12]:
filtered_df = new_df.loc[(new_df['theta']<=30) & (new_df['theta']>=-30)]
filtered_df
grouby_call_time = new_df.groupby("bat_last_call_time")
np.unique(filtered_df["bat_last_call_time"].values)

array([0.842, 1.21 , 1.306, 1.721, 1.829, 1.926, 1.97 , 2.071, 2.163,
       2.267, 4.289, 4.828, 4.87 , 5.016, 6.177, 6.294, 6.409, 6.496,
       7.34 , 7.565, 7.725, 7.919, 8.087, 8.146, 8.194, 8.254, 8.349,
       8.442, 8.705, 8.814, 8.868, 9.025])

In [13]:
filtered_df = new_df.loc[(new_df["emitter_id"]==0)]
filtered_df
grouby_call_time = new_df.groupby("bat_last_call_time")
np.unique(filtered_df["bat_last_call_time"].values)

array([1.21 , 1.262, 1.306, 1.356, 1.458, 1.567, 1.62 , 1.721, 1.829,
       1.872, 1.926, 1.97 , 2.071, 2.163, 2.267, 2.367, 2.412, 2.456,
       2.548, 2.656, 2.755, 2.864, 2.971, 4.733, 4.786, 4.828, 4.87 ,
       4.923, 5.016, 5.116, 5.226, 5.479, 5.524, 5.576, 5.629, 5.683,
       5.732, 5.791, 5.892, 5.991, 6.084, 6.294, 7.973, 8.029, 8.087,
       8.146, 8.194, 8.254, 8.349, 8.442, 8.705, 8.759, 8.814, 8.868,
       8.914, 8.971, 9.025, 9.131, 9.23 ])

In [15]:

#first call
df = grouby_call_time.get_group(1.21)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type", "bat_direction", "incident_direction", "reflected_from"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type,bat_direction,incident_direction,reflected_from
16,0.006,8.487741,70.273378,3.267469,1.21,25,direct,"Vector(0.741, 0.672)","Vector(2.398, 2.219)",None
17,0.006,8.487741,70.273378,3.267469,1.21,25,direct,"Vector(0.741, 0.672)","Vector(2.398, 2.219)",None
18,0.008,76.698430,71.045697,1.301278,1.21,0,echo,"Vector(0.741, 0.672)","Vector(-0.466, 1.215)",wall_obstacle_39
19,0.008,76.698430,71.045697,1.301278,1.21,0,echo,"Vector(0.741, 0.672)","Vector(-0.466, 1.215)",wall_obstacle_39
20,0.010,94.708030,70.226998,1.558098,1.21,0,echo,"Vector(0.741, 0.672)","Vector(-0.980, 1.211)",wall_obstacle_38
21,0.010,94.708030,70.226998,1.558098,1.21,0,echo,"Vector(0.741, 0.672)","Vector(-0.980, 1.211)",wall_obstacle_38

In [28]:
# grouby_call_time = new_df.groupby("bat_last_call_time")
#first call

df = grouby_call_time.get_group(1.712)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type", "bat_direction"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type,bat_direction
472,0.002,33.663880,69.719910,6.332009,1.712,17,echo,"Vector(0.240, 0.971)"
473,0.002,33.663880,69.719910,6.332009,1.712,17,echo,"Vector(0.240, 0.971)"
474,0.002,28.998095,73.882554,5.453876,1.712,18,echo,"Vector(0.240, 0.971)"
475,0.002,28.998095,73.882554,5.453876,1.712,18,echo,"Vector(0.240, 0.971)"
476,0.004,35.587489,62.498126,6.782643,1.712,17,echo,"Vector(0.240, 0.971)"
477,0.004,35.587489,62.498126,6.782643,1.712,17,echo,"Vector(0.240, 0.971)"
478,0.004,31.561373,66.437130,5.886577,1.712,18,echo,"Vector(0.240, 0.971)"
479,0.004,31.561373,66.437130,5.886577,1.712,18,echo,"Vector(0.240, 0.971)"
480,0.005,-133.567338,72.121243,0.846718,1.712,0,echo,"Vector(0.240, 0.971)"
481,0.005,-133.567338,72.121243,0.846718,1.712,0,echo,"Vector(0.240, 0.971)"
482,0.006,33.752206,61.476311,6.329864,1.712,18,echo,"Vector(0.240, 0.971)"
483,0.006,33.752206,61.476311,6.329864,1.712,18,echo,"Vector(0.240, 0.971)"
484,0.006,-100.002399,69.802515,0.875401,1.712,0,echo,"Vector(0.240, 0.971)"
485,0.006,-100.002399,69.802515,0.875401,1.712,0,echo,"Vector(0.240, 0.971)"
486,0.007,-75.875864,65.301754,1.145336,1.712,0,echo,"Vector(0.240, 0.971)"
487,0.007,-75.875864,65.301754,1.145336,1.712,0,echo,"Vector(0.240, 0.971)"
488,0.009,-62.410521,60.600632,1.532178,1.712,0,echo,"Vector(0.240, 0.971)"
489,0.009,-62.410521,60.600632,1.532178,1.712,0,echo,"Vector(0.240, 0.971)"
490,0.011,-100.444616,63.139835,0.871033,1.712,8,echo,"Vector(0.240, 0.971)"
491,0.011,-100.444616,63.139835,0.871033,1.712,8,echo,"Vector(0.240, 0.971)"

In [29]:

grouby_call_time = new_df.groupby("bat_last_call_time")
#first call
df = grouby_call_time.get_group(1.821)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type
492,0.002,35.542745,69.819334,6.258646,1.821,17,echo
493,0.002,35.542745,69.819334,6.258646,1.821,17,echo
494,0.004,-113.811840,63.716003,0.807747,1.821,8,echo
495,0.004,-113.811840,63.716003,0.807747,1.821,8,echo
496,0.005,37.339625,62.580646,6.715246,1.821,17,echo
497,0.005,37.339625,62.580646,6.715246,1.821,17,echo
498,0.005,-113.946566,70.102064,0.807543,1.821,0,echo
499,0.005,-113.946566,70.102064,0.807543,1.821,0,echo
500,0.006,-5.057241,79.329607,2.837858,1.821,21,direct
501,0.006,-5.057241,79.329607,2.837858,1.821,21,direct
502,0.006,-5.141267,96.541847,2.846838,1.821,21,echo
503,0.006,-5.141267,96.541847,2.846838,1.821,21,echo
504,0.006,-84.019599,66.026791,0.992514,1.821,0,echo
505,0.006,-84.019599,66.026791,0.992514,1.821,0,echo
506,0.008,3.335100,72.752385,3.087085,1.821,21,echo
507,0.008,3.335100,72.752385,3.087085,1.821,21,echo
508,0.008,-66.667586,61.156781,1.345308,1.821,0,echo
509,0.008,-66.667586,61.156781,1.345308,1.821,0,echo
510,0.009,-114.508207,60.088588,0.807185,1.821,21,echo
511,0.009,-114.508207,60.088588,0.807185,1.821,21,echo
512,0.010,10.459553,64.944619,3.384532,1.821,21,echo
513,0.010,10.459553,64.944619,3.384532,1.821,21,echo

In [30]:

grouby_call_time = new_df.groupby("bat_last_call_time")
#first call
df = grouby_call_time.get_group(2.021)
df[["delta_t", "theta", "all_spl_values", "distance_from_bat", "bat_last_call_time", "emitter_id", "type"]]

,delta_t,theta,all_spl_values,distance_from_bat,bat_last_call_time,emitter_id,type
546,0.002,71.125063,66.111128,9.239444,2.021,4,direct
547,0.002,71.125063,66.111128,9.239444,2.021,4,direct
548,0.002,58.627322,63.271680,9.068422,2.021,6,direct
549,0.002,58.627322,63.271680,9.068422,2.021,6,direct
550,0.002,71.113230,89.140393,9.249158,2.021,4,echo
551,0.002,71.113230,89.140393,9.249158,2.021,4,echo
552,0.002,58.628819,87.795548,9.078320,2.021,6,echo
553,0.002,58.628819,87.795548,9.078320,2.021,6,echo
554,0.003,36.520568,71.213111,5.531599,2.021,17,direct
555,0.003,36.520568,71.213111,5.531599,2.021,17,direct
556,0.003,36.426582,93.622622,5.535551,2.021,17,echo
557,0.003,36.426582,93.622622,5.535551,2.021,17,echo
558,0.005,38.357935,70.294914,5.993808,2.021,17,echo
559,0.005,38.357935,70.294914,5.993808,2.021,17,echo
560,0.007,-4.052587,80.676100,2.443538,2.021,21,direct
561,0.007,-4.052587,80.676100,2.443538,2.021,21,direct
562,0.007,-4.153787,97.921245,2.452444,2.021,21,echo
563,0.007,-4.153787,97.921245,2.452444,2.021,21,echo
564,0.009,40.025056,63.019983,6.456351,2.021,17,echo
565,0.009,40.025056,63.019983,6.456351,2.021,17,echo
566,0.009,5.410789,74.122134,2.704085,2.021,21,echo
567,0.009,5.410789,74.122134,2.704085,2.021,21,echo
568,0.009,-15.554642,60.559372,2.277552,2.021,21,echo
569,0.009,-15.554642,60.559372,2.277552,2.021,21,echo
570,0.011,13.168434,66.147724,3.019432,2.021,21,echo
571,0.011,13.168434,66.147724,3.019432,2.021,21,echo

In [21]:
df_2 = pd.read_pickle("./JammingExperiment/Data/IntermediateData/debug13/bat0_hearing_data.pkl")

In [ ]:
df_3 = pd.read_pickle("./JammingExperiment/Data/IntermediateData/debug15/history_dump_29.999.pkl")

[{'time': np.float64(0.0),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(5.0), np.float64(3.5))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.001),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(5.0), np.float64(3.501))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.002),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(5.0), np.float64(3.502))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.003),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99999), np.float64(3.503))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.004),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99998), np.float64(3.504))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.005),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99997), np.float64(3.505))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.006),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99995), np.float64(3.506))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.007),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99993), np.float64(3.507))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.008),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99991), np.float64(3.508))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.009),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99988), np.float64(3.509))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.01),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99985), np.float64(3.51))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.011),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99982), np.float64(3.511))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,
  'PROPENSITY_TO_CHANGE_DIRECTION': 0,
  'FRAME_RATE': 100,
  'CLEANUP_INTERVAL': 0.1,
  'CLEANUP_PLOT_DATA': 10000000,
  'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
  'NOISE_IN_CALL_RATE': 0.01,
  'CALL_DIRECTIONALITY': 7,
  'HEARING_DIRECTIONALITY': 2,
  'BAT_ROTATION_SPEED': 180,
  'BAT_FRONTAL_RANGE': 30,
  'IMPLEMENT_SNR': 'yes',
  'HEARING_ANGLE_THRESHOLD': 90,
  'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
  'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
  'SPL_THRESHOLD_FOR_ATTRACTION': 93,
  'SPL_THRESHOLD_FOR_REPULSION': 98,
  'SPATIAL_REFERENCE_FRAME': 'allocentric',
  'BAT_RADIAL_RESOLUTION': 0.002,
  'BAT_ANGULAR_RESOLUTION': 15,
  'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
  'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
  'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
  'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
  'BEHAVIOUR_RULE': 'consistency',
  'CONTROLLER_TYPE': 'presence',
  'STORE_HEARING': 'no',
  'JAMMER_RESOLUTION': 1,
  'TEMPORAL_MASKING_FN_TYPE': 'full',
  'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'},
 {'time': np.float64(0.012),
  'bat_call_time': [-inf],
  'bat_positions': [(np.float64(4.99979), np.float64(3.512))],
  'SOUND_SPEED': 343,
  'SIM_DURATION': 30,
  'TIME_STEP': 0.001,
  'ARENA_WIDTH': 10,
  'ARENA_LENGTH': 7,
  'WALL_RESOLUTION': 0.51,
  'NUM_BATS': 1,
  'BAT_SPEED': 1,
  'BAT_FAST_SPEED': 1,
  'BAT_RADIUS': 0.125,
  'CALL_DURATION': 2,
  'CALL_RATE': 10,
  'CALL_RATE_FAST': 10,
  'EMITTED_SPL': 80,
  'HEARING_THRESHOLD': 40,
  'OBSTACLE_COUNT': 0,
  'OBSTACLE_RADIUS': 0.075,
  'AIR_ABSORPTION': 1,
  'REFLECTION_LOSS': 24,
  'REFLECTION_LOSS_WALL': 10,

In [6]:
df_3[0]

{'time': np.float64(0.0),
 'bat_call_time': [-inf],
 'bat_positions': [(np.float64(5.0), np.float64(3.5))],
 'SOUND_SPEED': 343,
 'SIM_DURATION': 30,
 'TIME_STEP': 0.001,
 'ARENA_WIDTH': 10,
 'ARENA_LENGTH': 7,
 'WALL_RESOLUTION': 0.51,
 'NUM_BATS': 1,
 'BAT_SPEED': 1,
 'BAT_FAST_SPEED': 1,
 'BAT_RADIUS': 0.125,
 'CALL_DURATION': 2,
 'CALL_RATE': 10,
 'CALL_RATE_FAST': 10,
 'EMITTED_SPL': 80,
 'HEARING_THRESHOLD': 40,
 'OBSTACLE_COUNT': 0,
 'OBSTACLE_RADIUS': 0.075,
 'AIR_ABSORPTION': 1,
 'REFLECTION_LOSS': 24,
 'REFLECTION_LOSS_WALL': 10,
 'PROPENSITY_TO_CHANGE_DIRECTION': 0,
 'FRAME_RATE': 100,
 'CLEANUP_INTERVAL': 0.1,
 'CLEANUP_PLOT_DATA': 10000000,
 'TIME_DELAY_FOR_DIRECTION_CHANGE': 0.008,
 'NOISE_IN_CALL_RATE': 0.01,
 'CALL_DIRECTIONALITY': 7,
 'HEARING_DIRECTIONALITY': 2,
 'BAT_ROTATION_SPEED': 180,
 'BAT_FRONTAL_RANGE': 30,
 'IMPLEMENT_SNR': 'yes',
 'HEARING_ANGLE_THRESHOLD': 90,
 'MINIMUM_SOUND_DETECTION_FRACTION': 0.75,
 'INCLUDE_DIRECT_SOUNDS_IN_RESPONSE': 'yes',
 'SPL_THRESHOLD_FOR_ATTRACTION': 93,
 'SPL_THRESHOLD_FOR_REPULSION': 98,
 'SPATIAL_REFERENCE_FRAME': 'allocentric',
 'BAT_RADIAL_RESOLUTION': 0.002,
 'BAT_ANGULAR_RESOLUTION': 15,
 'MEMORY_WINDOW_FOR_CONSISTENCY': 3,
 'CONVERT_GRIDS+TO_ONE_HOT_?': 'yes',
 'NUMBER_OF_CONSISTENT_IPIS_FOR_MOVEMENT': 2.0,
 'TIME_DELAY_THRESHOLD_FOR_REPULSION': 0.008,
 'BEHAVIOUR_RULE': 'consistency',
 'CONTROLLER_TYPE': 'presence',
 'STORE_HEARING': 'no',
 'JAMMER_RESOLUTION': 1,
 'TEMPORAL_MASKING_FN_TYPE': 'full',
 'OUTPUT_DIR_FOR_SIMULATION': '/sensitivity_analysis/paramset_0/'}

In [16]:
df_4 = pd.read_pickle("/media/adityamoger/T7 Shield/test_sensitivity/sensitivity_analysis/paramset_9/iteration_number_0/bat_hearing_data.pkl")
# df_4["bat_positions"][0][0]
df_4

Empty DataFrame
Columns: []
Index: []

In [17]:
df_4.keys()

RangeIndex(start=0, stop=0, step=1)

In [19]:

df_4 = pd.read_pickle("./JammingExperiment/Data/IntermediateData/debug17/bat_hearing_data.pkl")
# df_4["bat_positions"][0][0]
df_4

,all_spl_values,occurance_times,ids,origin,emitter_id,bat_direction,incident_direction,type,reflected_from,sound_object_id,bat_last_call_time,sound_direction,theta,bat_position,distance_from_bat,creation_time,received_spl,time,duration
0,"[68.70939630078358, 68.71349025133658]","[0.17500000000000002, 0.176]","[83213c93-c84c-4b12-a392-b4874ba66cc4, 83213c9...","(2, 7)",13,"Vector(-0.013, 1.000)","Vector(-0.701, 0.713)",direct,None,83213c93-c84c-4b12-a392-b4874ba66cc4,0.170,"Vector(0.000, -1.000)",-3.947023,"Vector(4.930, 4.022)",4.178077,0.162000,68.711,0.175,0.002
1,"[69.46708261055413, 69.4687462110513]","[0.47100000000000003, 0.47200000000000003]","[041d9a0b-650c-4507-a08a-60a52c1675cf, 041d9a0...","(2, 7)",13,"Vector(0.276, 0.961)","Vector(-0.828, 0.560)",direct,None,041d9a0b-650c-4507-a08a-60a52c1675cf,0.469,"Vector(0.000, -1.000)",7.443666,"Vector(5.130, 4.883)",3.778960,0.459000,69.468,0.471,0.002
2,[68.84383145067137],[0.482],[65a437c7-2618-419c-8867-eb9ce3a4aca7],"(4.59002, 6.9999)",0,"Vector(0.276, 0.961)","Vector(-0.254, 0.967)",echo,wall_obstacle_34,65a437c7-2618-419c-8867-eb9ce3a4aca7,0.469,"Vector(0.245, -0.969)",-33.767068,"Vector(5.138, 4.912)",2.159105,0.475393,68.844,0.482,0.001
3,[69.04988338497411],[0.482],[19c2fa18-0231-4ffc-8b2d-238dff3ae0a3],"(5.1, 6.9999)",0,"Vector(0.276, 0.961)","Vector(-0.018, 1.000)",echo,wall_obstacle_35,19c2fa18-0231-4ffc-8b2d-238dff3ae0a3,0.469,"Vector(0.013, -1.000)",-47.427110,"Vector(5.138, 4.912)",2.088635,0.475198,69.050,0.482,0.001
4,[68.09029974343673],[0.482],[108da644-1e2e-43d8-8115-c4a917576a84],"(5.60998, 6.9999)",0,"Vector(0.276, 0.961)","Vector(0.220, 0.975)",echo,wall_obstacle_36,108da644-1e2e-43d8-8115-c4a917576a84,0.469,"Vector(-0.221, -0.975)",-61.206206,"Vector(5.138, 4.912)",2.140845,0.475355,68.090,0.482,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1708,"[71.25072320033593, 71.27705967731235]","[29.913, 29.914]","[5d93f245-19a7-48fa-81ef-9179c4d6fc45, 5d93f24...","(9.99996, 2.03991)",29,"Vector(0.231, 0.973)","Vector(0.648, 0.762)",echo,wall_obstacle_16,5d93f245-19a7-48fa-81ef-9179c4d6fc45,29.906,"Vector(-0.440, -0.898)",-88.856660,"Vector(9.378, 1.309)",0.959730,29.909623,71.264,29.913,0.002
1709,"[74.4981075778728, 74.51886371987524]","[29.915, 29.916]","[577aa8da-9617-4f1b-a948-8493747aa7c3, 577aa8d...","(9.99996, 2.54991)",0,"Vector(0.231, 0.973)","Vector(0.449, 0.894)",echo,wall_obstacle_17,577aa8da-9617-4f1b-a948-8493747aa7c3,29.906,"Vector(-0.444, -0.896)",-75.146064,"Vector(9.380, 1.315)",1.382312,29.910115,74.508,29.915,0.002
1710,"[66.06289848083415, 66.08366400509058]","[29.916, 29.917]","[31033f0f-8c56-418e-bf91-84c6fecced56, 31033f0...","(9.99996, 2.54991)",29,"Vector(0.231, 0.973)","Vector(0.449, 0.893)",echo,wall_obstacle_17,31033f0f-8c56-418e-bf91-84c6fecced56,29.906,"Vector(-0.365, -0.931)",-75.174762,"Vector(9.380, 1.318)",1.379393,29.910985,66.073,29.916,0.002
1711,"[69.0500599614192, 69.06653782370829]","[29.917, 29.918]","[995c25ad-9212-4e52-a206-a9f7e294306f, 995c25a...","(9.99997, 3.05991)",0,"Vector(0.231, 0.973)","Vector(0.335, 0.942)",echo,wall_obstacle_18,995c25ad-9212-4e52-a206-a9f7e294306f,29.906,"Vector(-0.333, -0.943)",-68.069585,"Vector(9.381, 1.320)",1.846311,29.911487,69.058,29.917,0.002
1712,"[61.62169578511788, 61.63818988905974]","[29.918, 29.919]","[86e439bf-9381-478e-8e5e-f67d32e41d7b, 86e439b...","(9.99997, 3.0599)",29,"Vector(0.231, 0.973)","Vector(0.335, 0.942)",echo,wall_obstacle_18,86e439bf-9381-478e-8e5e-f67d32e41d7b,29.906,"Vector(-0.311, -0.951)",-68.079374,"Vector(9.382, 1.323)",1.843319,29.912385,61.630,29.918,0.002